[package]
name = "kvs"
version = "0.1.3"
authors = ["Javier L. <135663+xleyba@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
clap = "2.33.0"
